name: Deploy to VDS via Portainer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.REPOSITORY_NAME}}:${{ github.sha }}, ${{ secrets.DOCKER_USERNAME }}/${{ secrets.REPOSITORY_NAME}}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy via Portainer
        run: |
          # Get the current container ID
          CONTAINER_ID=$(curl -s -X GET "https://${{ secrets.PORTAINER_HOST }}/api/endpoints/${{ secrets.ENDPOINT_ID }}/docker/containers/${{ secrets.CONTAINER_NAME }}/json" \
          -H "X-API-Key: ${{ secrets.PORTAINER_API_TOKEN }}" \
          -H "Content-Type: application/json" | jq -r ".Id")

          # Recreate the container
          curl -s -X POST "https://${{ secrets.PORTAINER_HOST }}/api/docker/${{ secrets.ENDPOINT_ID }}/containers/$CONTAINER_ID/recreate" \
          -H "X-API-Key: ${{ secrets.PORTAINER_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"PullImage": true}'

          # Prune unused images
          curl -s -X POST "https://${{ secrets.PORTAINER_HOST }}/api/endpoints/${{ secrets.ENDPOINT_ID }}/docker/images/prune" \
          -H "X-API-Key: ${{ secrets.PORTAINER_API_TOKEN }}" \
          -H "Content-Type: application/json"
